entity_activity_tracker.activity_processor.credit_user_comment_creation:
  type: entity_activity_tracker.activity_processor.settings
  mapping:
    credit_user:
      type: integer

entity_activity_tracker.activity_processor.credit_user_content_creation:
  type: entity_activity_tracker.activity_processor.settings
  mapping:
    credit_user:
      type: integer
