# @todo: Add labels for all schema items.
entity_activity_tracker.settings:
  type: config_object
  label: 'Group settings'
  mapping:
    debug:
      type: 'integer'
      label: 'Enable debug logging'

# Define config entity (Tracker) schema.
entity_activity_tracker.entity_activity_tracker.*:
  type: config_entity
  label: 'Entity activity tracker config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    entity_type:
      type: string
      label: 'Entity Type'
    entity_bundle:
      type: string
      label: 'Entity Bundle'
    activity_processors:
      type: sequence
      label: 'Filter settings'
      sequence:
        type: entity_activity_tracker.activity_processor.[%key]
        label: 'Plugin configuration'


entity_activity_tracker.activity_processor:
  type: mapping
  label: 'Activity Processor settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    id:
      type: string
      label: 'Plugin id'

entity_activity_tracker.activity_processor.*:
  type: entity_activity_tracker.activity_processor

entity_activity_tracker.activity_processor.entity_create:
  type: entity_activity_tracker.activity_processor
  label: 'Activity Processor settings'
  mapping:
    activity_creation:
      type: integer
      label: 'Activity points for creation'
    activity_existing_enabler:
      type: boolean
      label: 'Allow alternative point when a tracker is created'
    activity_existing:
      type: integer
      label: 'Activity points for existing entities.'

entity_activity_tracker.activity_processor.entity_decay:
  type: entity_activity_tracker.activity_processor.settings
  mapping:
    decay:
      type: integer
    decay_type:
      type: string
    decay_granularity:
      type: integer

entity_activity_tracker.activity_processor.entity_edit:
  type: entity_activity_tracker.activity_processor.settings
  mapping:
    activity_edit:
      type: integer
